require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - Guardfile
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
MethodLength:
  Max: 15
  Enabled: false
  Enabled: false
RegexpLiteral:
  Exclude:
    - '**/*.gemspec'
    - '**/Guardfile'